import { describe, expect, it } from "vitest";

import { ManualMonotonicClock, parseCourseHoleIndex, parseCourseId, parseShotDirectionIndex, type PersistedRoundState } from "../domain/index.ts";
import type { Course } from "../course-loader/types.ts";
import type { ResolvedShot } from "../simulation/outcome.ts";
import { GAME_BASE_STATES, GameController, meterBlocksAt, renderPowerMeter, type GameWriter } from "./index.ts";

const course: Course = { schemaVersion: 1, id: "preview", name: "Preview Course", holes: [
  { id: "h1", number: 1, par: 4, tee: { x: 0, y: 0 }, cup: { x: 10, y: 0 }, boundary: { type: "polygon", points: [{ x: 0, y: 0 }, { x: 1, y: 0 }, { x: 1, y: 1 }] }, regions: [] },
  { id: "h2", number: 2, par: 3, tee: { x: 0, y: 0 }, cup: { x: 0, y: 10 }, boundary: { type: "polygon", points: [{ x: 0, y: 0 }, { x: 1, y: 0 }, { x: 1, y: 1 }] }, regions: [] },
  { id: "h4", number: 4, par: 5, tee: { x: 0, y: 0 }, cup: { x: -10, y: 0 }, boundary: { type: "polygon", points: [{ x: 0, y: 0 }, { x: 1, y: 0 }, { x: 1, y: 1 }] }, regions: [] },
] };
const id = parseCourseId("preview"); const holeIndex = parseCourseHoleIndex(0); const parsedDirection = parseShotDirectionIndex(0);
if (id === undefined || holeIndex === undefined || parsedDirection === undefined) throw new Error("fixture invalid");
const direction = parsedDirection;
const initial: PersistedRoundState = { kind: "persisted-round", courseId: id, currentHoleIndex: holeIndex, lie: { x: 0, y: 0 }, selectedClub: "driver", shotDirectionIndex: direction, holeScores: [], status: "active" };
class Writer implements GameWriter { shots = 0; terminals = 0; checkpoints = 0; fail = false; async commitShot(): Promise<number> { this.shots += 1; if (this.fail) throw new Error("disk"); return this.shots; } async append(entry: Parameters<GameWriter["append"]>[0]): Promise<number> { if (entry.kind === "round-terminal") this.terminals += 1; else this.checkpoints += 1; return this.terminals + this.checkpoints; } }
function shot(terminal: ResolvedShot["terminal"] = "rest"): ResolvedShot { return { shotId: "shot-1", preShotLie: { x: 0, y: 0 }, inputs: { club: "driver", directionIndex: direction, power: .1 }, landingPosition: { x: 1, y: 0 }, finalPosition: terminal === "cup" ? { x: 10, y: 0 } : { x: 1, y: 0 }, terminal, resultingSpeed: 0, elapsed: .1, resultingRound: { lie: terminal === "cup" ? { x: 10, y: 0 } : { x: 1, y: 0 }, playedStrokes: 1, penaltyStrokes: terminal === "water" || terminal === "out-of-bounds" ? 1 : 0, selectedClub: "driver", directionIndex: direction }, keyframes: [{ elapsed: 0, position: { x: 0, y: 0 }, speed: 1 }] }; }
function makeGame(terminal: ResolvedShot["terminal"] = "rest"): { game: GameController; clock: ManualMonotonicClock; writer: Writer } { const clock = new ManualMonotonicClock(); const writer = new Writer(); return { game: new GameController({ course, state: initial, writer, clock, shotId: () => "shot-1", resolve: () => shot(terminal) }), clock, writer }; }
async function flush(): Promise<void> { await Promise.resolve(); await Promise.resolve(); }

describe("V2-T10 FSM and game component", () => {
  it("AC-UI-001-01 enumerates exactly the nine base states and resize-paused wrapper", () => { expect(GAME_BASE_STATES).toEqual(["intro", "aiming", "metering", "committing", "playback", "penalty-notice", "hole-summary", "round-summary", "confirm-abandon"]); });
  it("AC-GME-001-01 starts Preview Hole 1 immediately with Driver and quantized Cup direction", () => { const { game } = makeGame(); expect(game.round.selectedClub).toBe("driver"); expect(game.round.shotDirectionIndex).toBe(0); expect(game.introText).toBe("Preview Course — Hole 1 — Par 4"); });
  it("AC-GME-001-02 persists aim and resets Driver/direction at a new Hole", async () => { const { game, clock } = makeGame("cup"); clock.advanceBy(1_000); game.tick(); game.key("ArrowDown"); game.key(" "); game.key("release"); game.key(" "); await flush(); clock.advanceBy(100); game.tick(); game.key("Enter"); await flush(); expect(game.round.selectedClub).toBe("driver"); expect(game.round.shotDirectionIndex).toBe(4); });
  it("AC-GME-001-03 summary text is input driven and scorecard is ordered", () => { const { game, clock } = makeGame(); clock.advanceBy(1_000); game.tick(); expect(game.state.kind).toBe("aiming"); });
  it("AC-GME-001-04 intro is one second active time and resize freezes it", () => { const { game, clock } = makeGame(); clock.advanceBy(999); game.tick(); game.resize(59, 20); clock.advanceBy(5_000); game.resize(60, 20); game.tick(); expect(game.state.kind).toBe("intro"); clock.advanceBy(1); game.tick(); expect(game.state.kind).toBe("aiming"); });
  it("AC-GME-001-05 notices are two seconds and no timer exists after reload", () => { const { game, clock } = makeGame("water"); clock.advanceBy(1_000); game.tick(); game.key(" "); game.key("release"); game.key(" "); return flush().then(() => { clock.advanceBy(100); game.tick(); expect(game.state.kind).toBe("penalty-notice"); clock.advanceBy(2_000); game.tick(); expect(game.state.kind).toBe("aiming"); }); });
  it("AC-GME-002-01 scores normal, Water, and Out-of-Bounds officially", () => { expect(shot("rest").resultingRound).toMatchObject({ playedStrokes: 1, penaltyStrokes: 0 }); expect(shot("water").resultingRound).toMatchObject({ playedStrokes: 1, penaltyStrokes: 1 }); expect(shot("out-of-bounds").resultingRound).toMatchObject({ playedStrokes: 1, penaltyStrokes: 1 }); });
  it("AC-GME-002-02 exposes playedStrokes, penaltyStrokes, holeScore, and roundScore", () => { const { game } = makeGame(); expect(game.holeScore()).toBe(0); expect(game.roundScore()).toBe(0); });
  it("AC-GME-002-03 Preview scorecard Course fixture is Holes 1, 2, 4, par 12", () => { expect(course.holes.map((hole) => hole.number)).toEqual([1, 2, 4]); expect(course.holes.reduce((n, hole) => n + hole.par, 0)).toBe(12); });
  it("AC-UI-001-02 deterministically ignores invalid input in intro", () => { const { game } = makeGame(); game.key("ArrowLeft"); game.key("Q"); expect(game.state.kind).toBe("intro"); });
  it("AC-UI-001-03 permits club and direction mutation only while aiming", () => { const { game } = makeGame(); game.key("ArrowDown"); expect(game.round.selectedClub).toBe("driver"); });
  it("AC-UI-001-04 retry and queued Esc cannot duplicate a Shot", async () => { const { game, clock, writer } = makeGame(); clock.advanceBy(1_000); game.tick(); game.key(" "); game.key("release"); game.key(" "); game.key("Escape"); await flush(); expect(writer.shots).toBe(1); expect(game.closed).toBe(true); });
  it("AC-UI-002-01 covers every meter bin, boundaries, wrap, and event-time sample", () => { expect(Array.from({ length: 20 }, (_, i) => meterBlocksAt(i * 150))).toEqual([...Array.from({ length: 10 }, (_, i) => i + 1), ...Array.from({ length: 10 }, (_, i) => 10 - i)]); expect(meterBlocksAt(3_000)).toBe(1); });
  it("AC-UI-002-02 renders exact blocks and fixed color only", () => { expect(renderPowerMeter(3)).toEqual({ blocks: "███", color: "#ed8796" }); });
  it("AC-UI-002-03 held/repeated key cannot start and stop a meter", () => { const { game, clock } = makeGame(); clock.advanceBy(1_000); game.tick(); game.key(" "); game.key(" ", clock.now(), true); expect(game.state.kind).toBe("metering"); });
  it("AC-UI-002-04 resize and confirmation freeze meter then resume offset", () => { const { game, clock } = makeGame(); clock.advanceBy(1_000); game.tick(); game.key(" "); clock.advanceBy(150); game.resize(59, 19); clock.advanceBy(5_000); game.resize(60, 20); expect(game.meterBlocks).toBe(2); game.key("Q"); clock.advanceBy(5_000); game.key("N"); expect(game.meterBlocks).toBe(2); });
  it("AC-UI-003-01 wraps and resumes each base state safely", () => { const { game } = makeGame(); game.resize(59, 20); expect(game.state.kind).toBe("resize-paused"); game.resize(60, 20); expect(game.state.kind).toBe("intro"); });
  it("AC-UI-003-02 suspension freezes active timers", () => { const { game, clock } = makeGame(); game.resize(59, 20); clock.advanceBy(9_000); game.resize(60, 20); expect(game.state.kind).toBe("intro"); });
  it("AC-UI-003-03 queued actions survive resize without early consumption", () => { const { game, clock } = makeGame("rest"); clock.advanceBy(1_000); game.tick(); game.key(" "); game.key("release"); game.key(" "); game.key("Escape"); game.resize(59, 20); expect(game.closed).toBe(false); });
  it("AC-UI-003-04 threshold is exactly 60 by 20", () => { const { game } = makeGame(); game.resize(59, 20); expect(game.state.kind).toBe("resize-paused"); game.resize(60, 19); expect(game.state.kind).toBe("resize-paused"); game.resize(60, 20); expect(game.state.kind).toBe("intro"); });
  it("AC-UI-004-01 Escape cancels uncommitted meter without a Stroke", () => { const { game, clock, writer } = makeGame(); clock.advanceBy(1_000); game.tick(); game.key(" "); game.key("Escape"); expect(writer.shots).toBe(0); expect(game.closed).toBe(false); });
  it("AC-UI-004-02 confirmation accept/cancel retains prior state", () => { const { game, clock } = makeGame(); clock.advanceBy(1_000); game.tick(); game.key("Q"); expect(game.state.kind).toBe("confirm-abandon"); game.key("N"); expect(game.state.kind).toBe("aiming"); });
  it("AC-UI-004-03 confirmed abandonment writes terminal before close", async () => { const { game, clock, writer } = makeGame(); clock.advanceBy(1_000); game.tick(); game.key("Q"); game.key("Y"); await flush(); expect(writer.terminals).toBe(1); expect(game.closed).toBe(true); });
});
