import { mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { describe, expect, it } from "vitest";

import type { PersistedRoundState } from "../domain/index.ts";
import { GOLF_ENTRY_MIGRATIONS, GOLF_BRANCH_REFERENCE_TYPE, RoundMutationWriter, RoundStore, parseGolfEntry, reconstructActiveBranch, reconstructRound, type BranchEntryLike, type GolfEntryV1 } from "./index.ts";

const snapshot = JSON.stringify({ schemaVersion: 1, id: "tiny", name: "Tiny", holes: [{ id: "tiny-hole", number: 1, par: 3, boundary: { type: "polygon", points: [{ x: 0, y: 0 }, { x: 4, y: 0 }, { x: 4, y: 4 }, { x: 0, y: 4 }] }, tee: { x: 1, y: 1 }, cup: { x: 2, y: 2 }, regions: [{ terrain: "green", shape: { type: "polygon", points: [{ x: 0, y: 0 }, { x: 4, y: 0 }, { x: 4, y: 4 }, { x: 0, y: 4 }] } }] }] });
const state = (status: PersistedRoundState["status"] = "active", lie = { x: 1, y: 1 }): PersistedRoundState => ({ kind: "persisted-round", courseId: "tiny" as PersistedRoundState["courseId"], currentHoleIndex: 0 as PersistedRoundState["currentHoleIndex"], lie, selectedClub: "driver", shotDirectionIndex: 0 as PersistedRoundState["shotDirectionIndex"], holeScores: [], status });
const start = (roundId = "round-a", branchId = "session-a"): GolfEntryV1 => ({ entryVersion: 1, roundId, revision: 0, kind: "round-start", payload: { courseSnapshot: snapshot, state: state(), branchId } });
const shot = (revision = 1, shotId = "shot-a"): GolfEntryV1 => ({ entryVersion: 1, roundId: "round-a", revision, kind: "shot", payload: { state: state("active", { x: 2, y: 1 }), shot: { shotId, preShotLie: { x: 1, y: 1 }, inputs: { club: "driver", directionIndex: 0, power: 1 }, landingPosition: { x: 2, y: 1 }, finalPosition: { x: 2, y: 1 }, terminal: "rest", resultingSpeed: 0, elapsed: 1, resultingRound: { lie: { x: 2, y: 1 }, playedStrokes: 1, penaltyStrokes: 0, selectedClub: "driver", directionIndex: 0 } } } });
const branch = (refs: readonly { roundId: string; revision: number }[]): BranchEntryLike[] => [{ type: "session", id: "root", parentId: null, timestamp: "2026-01-01T00:00:00Z" }, ...refs.map((ref, i) => ({ type: "custom", id: `golf-${i}`, parentId: i === 0 ? "root" : `golf-${i - 1}`, timestamp: "2026-01-01T00:00:00Z", customType: GOLF_BRANCH_REFERENCE_TYPE, data: ref }))];
async function fixture(): Promise<{ root: string; store: RoundStore }> { const root = await mkdtemp(join(tmpdir(), "pi-golf-round-")); return { root, store: new RoundStore({ root: join(root, ".pi/golf/rounds") }) }; }

describe("V2-PER durable Round store", () => {
  it("AC-PER-001-02 confines append-only authority beneath .pi/golf/rounds", async () => { const { root, store } = await fixture(); try { await store.append(start()); expect(store.pathFor("round-a")).toBe(join(root, ".pi/golf/rounds/round-a.jsonl")); expect(() => store.pathFor("../settings")).toThrow(); const before = await readFile(store.pathFor("round-a"), "utf8"); await store.append(shot()); expect((await readFile(store.pathFor("round-a"), "utf8")).startsWith(before)).toBe(true); } finally { await rm(root, { recursive: true }); } });
  it("AC-PER-001-05 / AC-PER-003-04 interruption at every append boundary leaves predecessor or committed Shot", async () => { for (const boundary of ["open", "write", "file-sync", "directory-sync"] as const) { const { root, store } = await fixture(); try { await store.append(start()); const interrupted = new RoundStore({ root: join(root, ".pi/golf/rounds"), afterWrite: (at) => { if (at === boundary) throw new Error(`interrupt-${at}`); } }); if (boundary === "directory-sync") await expect(interrupted.append(shot())).resolves.toBeUndefined(); else await expect(interrupted.append(shot())).rejects.toThrow(`interrupt-${boundary}`); const recovered = await store.read("round-a"); expect([0, 1]).toContain(recovered.revision); } finally { await rm(root, { recursive: true }); } } });
  it("AC-PER-003-04 injects interruption after new-file directory sync", async () => { const { root } = await fixture(); try { const interrupted = new RoundStore({ root: join(root, ".pi/golf/rounds"), afterWrite: (at) => { if (at === "directory-sync") throw new Error("interrupt-directory-sync"); } }); await expect(interrupted.append(start())).rejects.toThrow("interrupt-directory-sync"); const recovered = new RoundStore({ root: join(root, ".pi/golf/rounds") }); await expect(recovered.read("round-a")).resolves.toMatchObject({ revision: 0 }); } finally { await rm(root, { recursive: true }); } });
  it("AC-PER-001-05 rejects a malformed committed line but discards an unterminated tail", async () => { const { root, store } = await fixture(); try { await store.append(start()); await writeFile(store.pathFor("round-a"), `${JSON.stringify(start())}\n{`); await expect(store.read("round-a")).resolves.toMatchObject({ revision: 0 }); await writeFile(store.pathFor("round-a"), `${JSON.stringify(start())}\n{bad}\n`); await expect(store.read("round-a")).rejects.toThrow("Malformed committed"); } finally { await rm(root, { recursive: true }); } });
  it("AC-PER-002-01 strictly round-trips every envelope kind", () => { const replacement: GolfEntryV1 = { entryVersion: 1, roundId: "round-a", revision: 1, kind: "round-replacement", payload: { successorRoundId: "round-b", successorStartRevision: 0, successorStart: start("round-b").payload as never } }; for (const entry of [start(), shot(), { entryVersion: 1, roundId: "round-a", revision: 1, kind: "checkpoint", payload: { state: state(), lifecycle: "aiming" } }, { entryVersion: 1, roundId: "round-a", revision: 1, kind: "round-terminal", payload: { status: "complete", state: state("complete") } }, replacement]) expect(parseGolfEntry(JSON.parse(JSON.stringify(entry)))).toEqual(entry); });
  it("AC-PER-002-02 / AC-PER-002-04 reject incoherent semantic chains without older fallback", () => { expect(() => reconstructRound([start(), { ...shot(), revision: 2 }])).toThrow(); expect(() => reconstructRound([start(), { ...shot(), payload: { ...(shot().payload as object), state: state() } }])).toThrow(); expect(() => reconstructRound([{ ...start(), entryVersion: 2 }])).toThrow(); });
  it("AC-PER-002-03 has an explicit empty V2 migration registry", () => { expect(GOLF_ENTRY_MIGRATIONS.size).toBe(0); expect(() => parseGolfEntry({ ...start(), entryVersion: 0 })).toThrow(); });
  it("AC-PER-003-01 / AC-PER-003-03 scope one writer and retain failed shot identity for exact retry", async () => { const { root, store } = await fixture(); try { await store.append(start()); let fail = true; const flaky = new RoundStore({ root: join(root, ".pi/golf/rounds"), beforeWrite: (at) => { if (fail && at === "write") throw new Error("disk failure"); } }); const one = RoundMutationWriter.forSession(flaky, "session-a", "round-a", 0); const same = RoundMutationWriter.forSession(flaky, "session-a", "round-a", 0); expect(same).toBe(one); await expect(one.commitShot((shot().payload as { shot: never }).shot, state("active", { x: 2, y: 1 }))).rejects.toThrow("disk failure"); expect(one.pendingShotId).toBe("shot-a"); await expect(one.commitShot((shot(1, "shot-b").payload as { shot: never }).shot, state())).rejects.toThrow("Another Shot"); fail = false; await expect(one.commitShot((shot().payload as { shot: never }).shot, state("active", { x: 2, y: 1 }))).resolves.toBe(1); expect((await store.read("round-a")).revision).toBe(1); } finally { await rm(root, { recursive: true }); } });
  it("AC-PER-004-01 checkpoints and AC-PER-004-02 terminal lifecycle are idempotent", () => { const checkpoint: GolfEntryV1 = { entryVersion: 1, roundId: "round-a", revision: 1, kind: "checkpoint", payload: { state: state(), lifecycle: "hole-summary" } }; const terminal: GolfEntryV1 = { entryVersion: 1, roundId: "round-a", revision: 2, kind: "round-terminal", payload: { status: "abandoned", state: state("abandoned") } }; expect(reconstructRound([start(), checkpoint, terminal])).toMatchObject({ lifecycle: "round-summary", terminal: true }); expect(() => reconstructRound([start(), terminal, shot(3)])).toThrow(); });
  it("AC-PER-004-04 requires an atomic identifiable successor and rejects predecessor resurrection", () => { const replacement: GolfEntryV1 = { entryVersion: 1, roundId: "round-a", revision: 1, kind: "round-replacement", payload: { successorRoundId: "round-b", successorStartRevision: 0, successorStart: start("round-b").payload as never } }; expect(reconstructRound([start(), replacement])).toMatchObject({ terminal: true, replacement: "round-b" }); expect(() => reconstructRound([start(), { ...replacement, payload: { successorRoundId: "round-b", successorStartRevision: 0 } }, shot(2)])).toThrow(); });
  it("AC-PER-001-03 / AC-PER-005-01 uses actual Pi getBranch entry shape for fork-before and fork-after Shot", async () => { const { root, store } = await fixture(); try { await store.append(start()); await store.append(shot()); await expect(reconstructActiveBranch(store, branch([{ roundId: "round-a", revision: 0 }]), "other-session")).resolves.toMatchObject({ revision: 0 }); await expect(reconstructActiveBranch(store, branch([{ roundId: "round-a", revision: 0 }, { roundId: "round-a", revision: 1 }]), "other-session")).resolves.toMatchObject({ revision: 1 }); const malformed = branch([{ roundId: "round-a", revision: 1 }]).at(0); if (malformed === undefined) throw new Error("Expected branch root."); await expect(reconstructActiveBranch(store, [{ ...malformed, type: "custom", customType: GOLF_BRANCH_REFERENCE_TYPE, data: {} }], "session-a")).rejects.toThrow("Malformed Golf"); } finally { await rm(root, { recursive: true }); } });
  it("AC-PER-005-02 ignores compaction but validates getBranch references", async () => { const { root, store } = await fixture(); try { await store.append(start()); const compacted: BranchEntryLike[] = [{ type: "session", id: "root", parentId: null, timestamp: "x" }, { type: "compaction", id: "compact", parentId: "root", timestamp: "x" }, { ...(branch([{ roundId: "round-a", revision: 0 }]).at(1) ?? (() => { throw new Error("Expected branch reference."); })()), parentId: "compact" }]; await expect(reconstructActiveBranch(store, compacted, "wrong-session")).resolves.toMatchObject({ roundId: "round-a" }); } finally { await rm(root, { recursive: true }); } });
  it("AC-PER-005-04 newest invalid Round fails visibly and closed", async () => { const { root, store } = await fixture(); try { await store.append(start()); await writeFile(store.pathFor("round-a"), `${JSON.stringify(start())}\n{bad}\n`); await expect(reconstructActiveBranch(store, [], "session-a")).rejects.toThrow(); } finally { await rm(root, { recursive: true }); } });
});
