import { mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { describe, expect, it } from "vitest";

import type { PersistedRoundState } from "../domain/index.ts";
import {
  GOLF_ENTRY_MIGRATIONS,
  RoundMutationWriter,
  RoundStore,
  parseGolfEntry,
  reconstructActiveBranch,
  reconstructRound,
  type GolfEntryV1,
} from "./index.ts";

const snapshot = JSON.stringify({ schemaVersion: 1, id: "tiny", name: "Tiny", holes: [{ id: "tiny-hole", number: 1, par: 3, boundary: { type: "polygon", points: [{ x: 0, y: 0 }, { x: 4, y: 0 }, { x: 4, y: 4 }, { x: 0, y: 4 }] }, tee: { x: 1, y: 1 }, cup: { x: 2, y: 2 }, regions: [{ terrain: "green", shape: { type: "polygon", points: [{ x: 0, y: 0 }, { x: 4, y: 0 }, { x: 4, y: 4 }, { x: 0, y: 4 }] } }] }] });
const state = (status: PersistedRoundState["status"] = "active"): PersistedRoundState => ({ kind: "persisted-round", courseId: "tiny" as PersistedRoundState["courseId"], currentHoleIndex: 0 as PersistedRoundState["currentHoleIndex"], lie: { x: 1, y: 1 }, selectedClub: "driver", shotDirectionIndex: 0 as PersistedRoundState["shotDirectionIndex"], holeScores: [], status });
const start = (roundId = "round-a", branchId = "branch-a"): GolfEntryV1 => ({ entryVersion: 1, roundId, revision: 0, kind: "round-start", payload: { courseSnapshot: snapshot, state: state(), branchId } });
const shot = (revision = 1, shotId = "shot-a"): GolfEntryV1 => ({ entryVersion: 1, roundId: "round-a", revision, kind: "shot", payload: { state: state(), shot: { shotId, preShotLie: { x: 1, y: 1 }, inputs: { club: "driver", directionIndex: 0, power: 1 }, landingPosition: { x: 2, y: 1 }, finalPosition: { x: 2, y: 1 }, terminal: "rest", resultingSpeed: 0, elapsed: 1, resultingRound: { lie: { x: 2, y: 1 }, playedStrokes: 1, penaltyStrokes: 0, selectedClub: "driver", directionIndex: 0 } } } });
async function fixture(): Promise<{ root: string; store: RoundStore }> { const root = await mkdtemp(join(tmpdir(), "pi-golf-round-")); return { root, store: new RoundStore({ root: join(root, ".pi/golf/rounds") }) }; }

describe("V2-PER durable Round store", () => {
  it("AC-PER-001-02 confines append-only authority beneath .pi/golf/rounds", async () => { const { root, store } = await fixture(); try { await store.append(start()); expect(store.pathFor("round-a")).toBe(join(root, ".pi/golf/rounds/round-a.jsonl")); expect(() => store.pathFor("../settings")).toThrow(); const before = await readFile(store.pathFor("round-a"), "utf8"); await store.append(shot()); expect((await readFile(store.pathFor("round-a"), "utf8")).startsWith(before)).toBe(true); } finally { await rm(root, { recursive: true }); } });
  it("AC-PER-001-05 / AC-PER-003-04 treat only an unterminated tail as uncommitted and sync boundaries", async () => { const { root, store } = await fixture(); try { const boundaries: string[] = []; const observed = new RoundStore({ root: join(root, ".pi/golf/rounds"), beforeWrite: (boundary) => { boundaries.push(boundary); } }); await observed.append(start()); expect(boundaries).toEqual(["open", "write", "file-sync", "directory-sync"]); await writeFile(store.pathFor("round-a"), `${JSON.stringify(start())}\n{`, "utf8"); await expect(store.read("round-a")).resolves.toMatchObject({ revision: 0 }); await writeFile(store.pathFor("round-a"), `${JSON.stringify(start())}\n{bad}\n`, "utf8"); await expect(store.read("round-a")).rejects.toThrow("Malformed committed"); } finally { await rm(root, { recursive: true }); } });
  it("AC-PER-002-01 strictly round-trips every envelope kind", () => { const entries: GolfEntryV1[] = [start(), shot(), { entryVersion: 1, roundId: "round-a", revision: 1, kind: "checkpoint", payload: { state: state(), lifecycle: "aiming" } }, { entryVersion: 1, roundId: "round-a", revision: 1, kind: "round-terminal", payload: { status: "complete", state: state("complete") } }, { entryVersion: 1, roundId: "round-a", revision: 1, kind: "round-replacement", payload: { successorRoundId: "round-b", successorStartRevision: 0 } }]; for (const entry of entries) expect(parseGolfEntry(JSON.parse(JSON.stringify(entry)))).toEqual(entry); });
  it("AC-PER-002-02 / AC-PER-002-04 fail closed for wrong IDs, revisions, ordering, malformed newest data", () => { expect(() => reconstructRound([start(), { ...shot(), revision: 2 }])).toThrow(); expect(() => reconstructRound([start(), { ...shot(), roundId: "round-b" }])).toThrow(); expect(() => reconstructRound([start(), { ...shot(), payload: {} }])).toThrow(); expect(() => reconstructRound([{ ...start(), entryVersion: 2 }])).toThrow(); });
  it("AC-PER-002-03 has an explicit empty V2 migration registry and no silent migration", () => { expect(GOLF_ENTRY_MIGRATIONS.size).toBe(0); expect(() => parseGolfEntry({ ...start(), entryVersion: 0 })).toThrow(); });
  it("AC-PER-003-01 / AC-PER-003-02 / AC-PER-003-03 serialize overlap and retry one shotId", async () => { const { root, store } = await fixture(); try { await store.append(start()); const entry = parseGolfEntry(shot()); if (entry.kind !== "shot") throw new Error("Expected Shot."); const writer = new RoundMutationWriter(store, "round-a", 0); expect(writer.beginShot("shot-a")).toBe(true); expect(writer.beginShot("shot-b")).toBe(false); await Promise.all([writer.commitShot(entry.payload.shot, state()), writer.commitShot(entry.payload.shot, state())]); expect((await store.read("round-a")).revision).toBe(1); } finally { await rm(root, { recursive: true }); } });
  it("AC-PER-004-01 checkpoints exact aiming state with no Shot", () => { expect(reconstructRound([start(), { entryVersion: 1, roundId: "round-a", revision: 1, kind: "checkpoint", payload: { state: state(), lifecycle: "aiming" } }]).lifecycle).toBe("aiming"); });
  it("AC-PER-004-02 / AC-PER-004-03 persist summary/terminal exactly once", () => { const terminal: GolfEntryV1 = { entryVersion: 1, roundId: "round-a", revision: 1, kind: "round-terminal", payload: { status: "abandoned", state: state("abandoned") } }; expect(reconstructRound([start(), terminal]).terminal).toBe(true); expect(() => reconstructRound([start(), terminal, shot(2)])).toThrow(); });
  it("AC-PER-004-04 replacement has one successor and never resurrects predecessor", () => { const replacement: GolfEntryV1 = { entryVersion: 1, roundId: "round-a", revision: 1, kind: "round-replacement", payload: { successorRoundId: "round-b", successorStartRevision: 0 } }; expect(reconstructRound([start(), replacement])).toMatchObject({ terminal: true, replacement: "round-b" }); expect(() => reconstructRound([start(), replacement, shot(2)])).toThrow(); });
  it("AC-PER-001-03 / AC-PER-005-01 branch fork references choose only the associated authoritative Round", async () => { const { root, store } = await fixture(); try { await store.append(start()); await store.append(shot()); const branch = [{ type: "custom", customType: "pi-golf-round-v1", data: { roundId: "round-a", revision: 1 } }]; await expect(reconstructActiveBranch(store, branch, "branch-a")).resolves.toMatchObject({ revision: 1 }); } finally { await rm(root, { recursive: true }); } });
  it("AC-PER-005-02 / AC-PER-005-03 ignores compaction/transient playback and resumes canonical lifecycle", () => { const round = reconstructRound([start(), { entryVersion: 1, roundId: "round-a", revision: 1, kind: "checkpoint", payload: { state: state(), lifecycle: "hole-summary" } }]); expect(round).not.toHaveProperty("playback"); expect(round.lifecycle).toBe("hole-summary"); });
  it("AC-PER-005-04 newest invalid Round visibly fails closed rather than older fallback", async () => { const { root, store } = await fixture(); try { await store.append(start()); await writeFile(store.pathFor("round-a"), `${JSON.stringify(start())}\n{bad}\n`); await expect(reconstructActiveBranch(store, [], "branch-a")).rejects.toThrow(); } finally { await rm(root, { recursive: true }); } });
});
